CREATE DATABASE IF NOT EXISTS TPDb;
USE TPDb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL,
    male BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    capacity INT NOT NULL,
    timestamp DATETIME NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT 0,
    mixed BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS event_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    eventId INT NOT NULL,
    comment VARCHAR(2048),
    state INT NOT NULL,
    timestamp DATETIME NULL,
    UNIQUE KEY unique_user_event (userId, eventId),
    CONSTRAINT FK_EVENT_USERS FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT FK_USER_EVENTS FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS event_guests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    male BOOLEAN NOT NULL DEFAULT 1,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    handicap DECIMAL(4,1),
    comment VARCHAR(2048),
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GUEST_EVENT FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS male BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rfeg VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS member_number VARCHAR(255) NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS mixed BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE event_guests ADD COLUMN IF NOT EXISTS male BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE event_guests MODIFY COLUMN IF EXISTS email VARCHAR(255) NULL;
ALTER TABLE event_guests MODIFY COLUMN IF EXISTS handicap DECIMAL(4,1) NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS price_members DECIMAL(8,2) NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS price_guests DECIMAL(8,2) NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS registration_close DATETIME NULL;

CREATE TABLE IF NOT EXISTS social_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tournamentId INT NULL,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    description TEXT NULL,
    registration_close DATETIME NULL,
    locked BOOLEAN NOT NULL DEFAULT 0,
    timestamp DATETIME NOT NULL,
    CONSTRAINT FK_SOCIAL_TOURNAMENT FOREIGN KEY (tournamentId) REFERENCES events(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS social_menus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    socialEventId INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT FK_MENU_SOCIAL FOREIGN KEY (socialEventId) REFERENCES social_events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS social_tables (
    id INT AUTO_INCREMENT PRIMARY KEY,
    socialEventId INT NOT NULL,
    number INT NOT NULL,
    capacity INT NOT NULL,
    CONSTRAINT FK_TABLE_SOCIAL FOREIGN KEY (socialEventId) REFERENCES social_events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS social_registrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    socialEventId INT NOT NULL,
    userId INT NULL,
    firstName VARCHAR(255) NULL,
    lastName VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    tableId INT NULL,
    menuId INT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SREG_EVENT FOREIGN KEY (socialEventId) REFERENCES social_events(id) ON DELETE CASCADE,
    CONSTRAINT FK_SREG_USER FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT FK_SREG_TABLE FOREIGN KEY (tableId) REFERENCES social_tables(id) ON DELETE SET NULL,
    CONSTRAINT FK_SREG_MENU FOREIGN KEY (menuId) REFERENCES social_menus(id)
);

ALTER TABLE social_registrations MODIFY COLUMN IF EXISTS menuId INT NULL;