CREATE DATABASE IF NOT EXISTS TPDb;
USE TPDb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    capacity INT NOT NULL,
    timestamp DATETIME NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS event_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    eventId INT NOT NULL,
    comment VARCHAR(2048),
    state INT NOT NULL,
    timestamp DATETIME NULL,
    CONSTRAINT FK_EVENT_USERS FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT FK_USER_EVENTS FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

ALTER TABLE event_users ADD UNIQUE KEY unique_user_event (userId, eventId);

CREATE TABLE IF NOT EXISTS event_guests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    handicap DECIMAL(4,1) NOT NULL,
    rfeg VARCHAR(255),
    comment VARCHAR(2048),
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GUEST_EVENT FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);