CREATE DATABASE IF NOT EXISTS TPDb;
USE TPDb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL,
    male BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    capacity INT NOT NULL,
    timestamp DATETIME NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT 0,
    mixed BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS event_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    eventId INT NOT NULL,
    comment VARCHAR(2048),
    state INT NOT NULL,
    timestamp DATETIME NULL,
    UNIQUE KEY unique_user_event (userId, eventId),
    CONSTRAINT FK_EVENT_USERS FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT FK_USER_EVENTS FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS event_guests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    male BOOLEAN NOT NULL DEFAULT 1,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    handicap DECIMAL(4,1),
    rfeg VARCHAR(255),
    comment VARCHAR(2048),
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GUEST_EVENT FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS male BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rfeg VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS member_number VARCHAR(255) NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS mixed BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE event_guests ADD COLUMN IF NOT EXISTS male BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE event_guests MODIFY COLUMN IF EXISTS email VARCHAR(255) NULL;
ALTER TABLE event_guests MODIFY COLUMN IF EXISTS handicap DECIMAL(4,1) NULL;